version: "3"


networks:
    webnet:
      driver: bridge
services:
  webapp:
    build: ./
    restart: on-failure
    networks:
      - webnet
    links:
      - database
    ports:
      - "8082:8082"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    networks:
      - webnet
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8080:80"

  database:
    image: mysql
    restart: on-failure
    volumes:
      - ./mysql-data:/var/lib/mysql:rw
    networks:
      - webnet
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: "login"
      MYSQL_USER: "ooc"
      MYSQL_PASSWORD: "muic"
      MYSQL_ROOT_PASSWORD: "12345"