version: "3"


networks:
    webnet:
      driver: bridge
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    # network_mode: "bridge"  
    networks:
      - webnet
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8080:80"


  database:
    image: mysql
    restart: on-failure
    volumes:
      - ./mysql-data:/var/lib/mysql:rw
    networks:
      - webnet
    # network_mode: "bridge"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "login"
      MYSQL_USER: "ooc"
      MYSQL_PASSWORD: "muic"
      MYSQL_ROOT_PASSWORD: "12345"
